apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
# especifica o tipo de objeto
kind: Deployment
metadata:
  name: second-app-deplyment
spec:
  replicas: 1
  # os pods que possuem essas labels devem ser controladas pelo deploy
  selector:
    matchLabels:
      app: second-app
      tier: backend
  # define como o pod deverá ser criado pelo deploy
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: diegopimenta/kub-first-app
