apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: diegopimenta/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            # path no container
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          # não funciona quando há mais replicas, apenas o próprio pod acessa
          # emptyDir: {}
          # as replicas agoram podem acessar, mas só se estiverem no mesmo node
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: host-pvc
