apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    # único modo disponível para o hostPath
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
